export * from "@/utils/DeferredPromise"
export {default as DeferredPromise} from "@/utils/DeferredPromise"
export {default as groupBy} from "@/utils/groupBy"
export {default as isBoolean} from "@/utils/isBoolean"
export {default as isColor} from "@/utils/isColor"
export {default as isFunction} from "@/utils/isFunction"
export {default as isNumber} from "@/utils/isNumber"
export {default as isObject} from "@/utils/isObject"
export {default as isString} from "@/utils/isString"
export {default as pipe} from "@/utils/pipe"
export * from "@/utils/reemplaceString"
export * from "@/types/RequiredAllProperties"
export * from "@/types/StrictObject"
export * from "@/types/globlas"
